[FEATURE] Role reshaping
idealista/mysql_role pull request #71
Opened 2021-06-01 15:08 UTC by marcelogalmor

### Description

Lately we've been making some changes to our roles and this role lags behind the rest of the roles in some aspects:

* There is no .gitattributes file: https://github.com/idealista/jira_role/blob/master/.gitattributes
* There is no travis email notification config: https://github.com/idealista/jira_role/blob/master/.travis.yml#L20-L25
* Some versions in the Pipfile could be updated, at least the patch version (be aware to not break CI): https://github.com/idealista/jira_role/blob/master/Pipfile
* Add ansible-lint as dependency in the Pipfile and its config: https://github.com/idealista/jira_role/blob/master/.ansible-lint. Include ansible-lint in molecule linting stage: https://github.com/idealista/jira_role/blob/master/molecule/default/molecule.yml#L8
* Some warnings may arise because of the introduction of ansible-lint. It could be positive to fix them.
 
### Why is this needed?

So the role is updated along all the roles

### Additional Information

N/A

2021-06-01 15:18 UTC, vicsufer requested changes
Looks great!

Just one small detail, we also need to change the README.md file to reflect the updated versions of ansible, molecule, etc

https://github.com/idealista/mysql_role/blob/master/README.md

2021-06-01 15:20 UTC, jperera approved these changes

2021-06-01 15:25 UTC, emepege approved these changes

2021-06-03 13:45 UTC, vicsufer approved these changes

2021-06-03 13:56 UTC, xtianae7 approved these changes

2021-06-04 07:30 UTC, blalop approved these changes

2021-06-04 08:56 UTC, merged